### ISSUE TITLE
Access to RUB-EP1 GitHub organization?

### ISSUE THREAD

**Issue by redeboer** [RUB-EP1/WiBaS#2]
Hi @maltealbrecht @JulianPychy,
@mmikhasenko and I were wondering if we could be made maintainers of the https://github.com/RUB-EP1 organization/namespace. We would like to use it for hosting repositories for EP1.

**Comment by mmikhasenko** [comment]
Hi @maltealbrecht, @JulianPychy 
EP1 people want to use github, finally! We can take over this organization

**Comment by maltealbrecht** [comment]
Sorry - just saw this. Sure, thats a good idea - I'll see what I can do!

**Comment by maltealbrecht** [comment]
I invited both of you as Owners.

**Comment by mmikhasenko** [comment]
Perfect, thanks, @maltealbrecht 
Just accepted

**Comment by redeboer** [comment]
Great, thanks a lot!
